services:
  postgres:
    container_name: auth-db-dt
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: auth_app
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-auth-dt
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local