eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



spring:

  application:
    name: auth-service


  datasource:
    #url: jdbc:postgresql://localhost:5432/auth_app
    #username: username
    #password: password
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
    username: postgres.uxdjecmrgvqalupolapz
    password: Supa92231411base
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: marwen
    password: marwen
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000



application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 day
      refresh-token :
        expiration: 604800000 # 7 days

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088
  servlet:
    context-path: /api/v1/
